baseURL: "http://localhost:1313/"
languageCode: en-us
title: Stacks of Scrolls
theme: ["PaperMod"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: 'G-VBYP6TM1D3'
privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true
    
markup: 
  goldmark:
    renderer: 
      unsafe: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Abhishek Benny
  description: ""
  keywords: [Blog, Portfolio, PaperMod]
  author: Abhishek Benny
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  #cover:
    #hiddenInList: true
  assets:
    favicon: /favicon.ico
    favicon16x16: /favicon-16x16.png
    favicon32x32: /favicon-32x32.png
    apple_touch_icon: /apple-touch-icon.png
    safari_pinned_tab: /safari-pinned-tab.svg

  profileMode:
    enabled: True # needs to be explicitly set
    title: Abhishek Benny
    subtitle: Data Scientist | Python, SQL, Machine Learning, Time-Series Analytics | Manufacturing & Financial Data | UAE (Resident Visa)
    imageUrl: "https://avatars.githubusercontent.com/u/245692955?v=4"
    imageWidth: 120
    imageHeight: 120
    imageTitle: profile picture
    buttons:
      - name: Blog
        url: /stacks/
      - name: CV/Resume
        url: /files/abhishek_benny.pdf
        newTab: true

  socialIcons:
    - name: email
      url: mailto:abhishekbenny@deepam.net
    - name: Linkedin
      url: https://www.linkedin.com/in/abhishekbenny/
    - name: github
      url: https://github.com/abhishekbenny25

menu:
  main:
    - identifier: blog
      name: Blog
      url: /stacks/
      weight: 10
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
    - identifier: about
      name: About Me
      url: /
      weight: 5
    - identifier: cv
      name: CV
      url: /files/abhishek_benny.pdf
      weight: 30
      params:
        newTab: true

caches:
  images:
    dir: :cacheDir/images